---
driver:
  name: docker
  use_sudo: false
  privileged: true
  require_chef_omnibus: false

platforms:
  - name: ubuntu-14.04
  - name: centos-7

provisioner:
  name: salt_solo
  #log_level: quiet
  require_chef: false
  formula: consul

suites:
  - name: consul
    provisioner:
      state_top:
        base:
          '*':
            - consul
      pillars-from-files:
        consul.sls: pillar.example
      pillars:
        top.sls:
          base:
            '*':
              - consul
