---
driver:
  name: docker
  use_sudo: false
  privileged: true
  require_chef_omnibus: false

platforms:
  - name: ubuntu-14.04
    driver_config:
      run_command: /sbin/init
  - name: centos-7
    driver_config:
      run_command: /usr/lib/systemd/systemd

provisioner:
  name: salt_solo
  #log_level: quiet
  require_chef: false
  formula: consul

suites:
  - name: consul
    provisioner:
      state_top:
        base:
          '*':
            - consul
      pillars:
        consul.sls:
          consul:
            service: True
            config:
              server: True
              bind_addr: 0.0.0.0
              enable_debug: True
              datacenter: eu
              encrypt: "RIxqpNlOXqtr/j4BgvIMEw=="
              bootstrap_expect: 3
              retry_interval: 15s
              retry_join:
                - 1.1.1.1
                - 2.2.2.2
        top.sls:
          base:
            '*':
              - consul
