sudo: required
language: python
services: 
  - docker

before_install:
  - bundle install

env:
  matrix:
    - INSTANCE: consul-ubuntu-1404
    - INSTANCE: consul-centos-7

script:
  - bundle exec kitchen verify ${INSTANCE}
